name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      # Путь к Android SDK
      ANDROID_HOME: /usr/local/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: '34.0.0'

    - name: Accept Android Licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Set local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > app/local.properties

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build Release APK
      run: ./gradlew clean assembleRelease --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: nash-sklad-release-apk
        path: app/build/outputs/apk/release/app-release.apk
